In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_excel('data/Bolsonaro + Lula - Validado.xlsx')
df

,Unnamed: 0,DataColeta,Perfil,DataPost,DiaDaSemana,Plays,Curtidas,Comentarios,Compart.,Texto,...,ID,Duracao,Duração Classificada,Retórica Aristotélica,Dispositivo Retórico,Tipo de conteúdo,Abordagem,Tonalidade,Main character,Texto / Hashtag
0,1,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,248400,24400,1083,1566,#jairbolsonaro #bolsonaro #palavras #president...,...,7114971700365692165,57.93,Curto,Pathos,Political Statement,Campaign Act,Acclamation,Neutral,Self alone,Hashtag
1,2,2022-10-02,lulaoficial,2022-06-30 00:00:00,quinta-feira,196800,11700,809,589,Alô alô geração tiktoker! Imagina só um #gover...,...,7115033431473474822,2023-03-17 00:00:00,Muito curto,Pathos,Political Statement,Political-Purposeful,Acclamation,Neutral,Self alone,Texto + Hashtag
2,3,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,82000,9163,480,1140,#emprego #jair #bolsonaro #jairbolsonaro #pres...,...,7115050482179050758,17.13,Muito curto,Logos,Fact/Statistic,Political-Purposeful,Acclamation,Positive,Self alone,Hashtag
3,4,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,42300,3485,198,355,#jairbolsonaro #bolsonaro #jair #presidente #m...,...,7115120078982630661,52.54,Curto,Ethos,Commitment,Political-Purposeful,Acclamation,Positive,Self + voters,Hashtag
4,5,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,168500,22100,666,967,#jairbolsonaro #bolsonaro #brasil #descontraca...,...,7115161088219565317,34.48,Curto,Nenhum,Humor,Personal,Acclamation,Positive,Self alone,Hashtag
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,565,2022-10-30,bolsonaromessiasjair,2022-10-29 17:13:46,sábado,191600,23500,1611,1499,- Belo Horizonte/MG. - Presidente Jair Bolsona...,...,7160017587160485125,51.34,Curto,Ethos,Commitment,Campaign Act,Acclamation,Positive,Self + voters,Texto + Hashtag
565,566,2022-10-30,lulaoficial,2022-10-29 17:52:50,sábado,322000,33900,540,1361,Todo mundo tem um vizinho que vota pela famíli...,...,7160037888611126534,2023-02-15 00:00:00,Muito curto,Ethos,Advertisement,Campaign Act,Acclamation,Positive,Nenhum,Texto + Hashtag
566,567,2022-10-30,lulaoficial,2022-10-29 18:52:45,sábado,317800,25000,1166,2525,Lula criou o mei e vai fazer ainda mais pelo p...,...,7160041692911930630,85.1,Normal,Ethos,Political Statement,Political-Purposeful,Attack,Negative,Self alone,Texto + Hashtag
567,568,2022-10-30,lulaoficial,2022-10-29 20:52:41,sábado,60700,4807,374,826,Ta chegando a hora de votar #lulapresidente #lula,...,7160077729751207174,12.93,Muito curto,Ethos,Advertisement,Campaign Act,Acclamation,Positive,Self alone,Texto + Hashtag
568,569,2022-10-30,lulaoficial,2022-10-29 21:52:34,sábado,107800,17100,965,2338,Obrigado São Paulo ❤️🇧🇷🇧🇷1️⃣3️⃣⭐️ #lulapreside...,...,7160091637970963718,49.19,Curto,Ethos,Thanks,Campaign Act,Acclamation,Positive,Self alone,Texto + Hashtag

## Tratando coluna de duração

In [3]:
def day_for_flaot(x):
  if(isinstance(x, datetime.datetime)):
    x = float(f"{x.day}.{x.month}")
  return x

In [4]:
df['Duracao'] = df['Duracao'].apply(day_for_flaot)

## Observando primeiro quartil antes e depois do filtro de porcentagem

In [5]:
data = pd.read_csv('data/GoogleVision.csv')
data = data.loc[data['ID'].isin(df['ID'])] # Filtrando post que estão no dataset do tiktok
data = data.loc[data['Subclass'] != 'text']
data_test = data.loc[data['Percent'] >= 0.74]

In [6]:
print('Dados anteriores')
print('Quantidade de IDs:', len(data['ID'].unique()))
print('Quantidade de de classes:', data['ID'].count())
print('Mediana:', data['Percent'].median())
print('Média:', data['Percent'].mean())
print('1º Quartil:', data['Percent'].quantile(.25))
print('-----------------------------')
print('Dados posteriores')
print('Quantidade de IDs:', len(data_test['ID'].unique()))
print('Quantidade de de classes:', data_test['ID'].count())
print('Mediana:', data_test['Percent'].median())
print('Média:', data_test['Percent'].mean())
print('1º Quartil:', data_test['Percent'].quantile(.25))

Dados anteriores
Quantidade de IDs: 569
Quantidade de de classes: 7221
Mediana: 0.83
Média: 0.8233970364215483
1º Quartil: 0.74
-----------------------------
Dados posteriores
Quantidade de IDs: 569
Quantidade de de classes: 5591
Mediana: 0.87
Média: 0.8719477732069396
1º Quartil: 0.8

In [7]:
print(7221 * .25)
print(7221 - 1805.25)

1805.25
5415.75

## Montando dataset com colunas em dummy

In [8]:
new_data = []
for id in data_test['ID'].unique():
  row = {'ID': id}
  for classe in data_test.loc[data_test['ID'] == id]['Class'].values:
    row[classe] = 1
  new_data.append(row)

new_data = pd.DataFrame(new_data)
new_data.fillna(0, inplace=True)
print(new_data)

                      ID  Public address system  Face  Spokesperson  \
0    7114971700365692165                    1.0   1.0           1.0
1    7115033431473474822                    0.0   0.0           0.0
2    7115050482179050758                    0.0   0.0           0.0
3    7115120078982630661                    0.0   0.0           0.0
4    7115161088219565317                    0.0   0.0           1.0
..                   ...                    ...   ...           ...
564  7160017587160485125                    0.0   0.0           0.0
565  7160037888611126534                    0.0   0.0           0.0
566  7160041692911930630                    0.0   0.0           1.0
567  7160077729751207174                    0.0   0.0           0.0
568  7160091637970963718                    0.0   0.0           0.0

     Audio equipment  Forehead  Gesture  Head  Person  Microphone  ...  Fluid  \
0                1.0       1.0      1.0   1.0     1.0         1.0  ...    0.0
1                0.0       1.0      1.0   0.0     0.0         0.0  ...    0.0
2                0.0       1.0      0.0   0.0     0.0         0.0  ...    0.0
3                0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
4                0.0       0.0      1.0   0.0     1.0         1.0  ...    0.0
..               ...       ...      ...   ...     ...         ...  ...    ...
564              0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
565              0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
566              0.0       0.0      1.0   0.0     1.0         1.0  ...    0.0
567              0.0       1.0      0.0   0.0     1.0         0.0  ...    0.0
568              0.0       0.0      0.0   0.0     0.0         0.0  ...    0.0

     Guitar  Guitar accessory  String instrument accessory  Speaker  \
0       0.0               0.0                          0.0      0.0
1       0.0               0.0                          0.0      0.0
2       0.0               0.0                          0.0      0.0
3       0.0               0.0                          0.0      0.0
4       0.0               0.0                          0.0      0.0
..      ...               ...                          ...      ...
564     0.0               0.0                          0.0      0.0
565     0.0               0.0                          0.0      0.0
566     0.0               0.0                          0.0      0.0
567     0.0               0.0                          0.0      0.0
568     0.0               0.0                          0.0      0.0

     Serveware  Drinkware  Coffee cup  Cup  Vegetation
0          0.0        0.0         0.0  0.0         0.0
1          0.0        0.0         0.0  0.0         0.0
2          0.0        0.0         0.0  0.0         0.0
3          0.0        0.0         0.0  0.0         0.0
4          0.0        0.0         0.0  0.0         0.0
..         ...        ...         ...  ...         ...
564        0.0        0.0         0.0  0.0         0.0
565        0.0        0.0         0.0  0.0         0.0
566        0.0        0.0         0.0  0.0         0.0
567        0.0        0.0         0.0  0.0         0.0
568        0.0        0.0         0.0  0.0         1.0

[569 rows x 382 columns]

## Pegando quantidade de classes mais presentes nos dados

In [9]:
qtn_class = data_test.groupby('Class').size().reset_index(name='Total').sort_values('Total')
qtn_class

              Class  Total
0           Abdomen      1
304          Sports      1
303     Sport venue      1
117  Fashion design      1
119           Fence      1
..              ...    ...
130            Font    172
133        Forehead    173
142         Gesture    212
180             Joy    242
242          Person    406

[381 rows x 2 columns]

In [54]:
amazon = pd.read_csv(r'D:\documents\PIC\Visions\data\result_not_duplicates.csv')
amazon = amazon.loc[~amazon['ID'].str.contains('lula')]
amazon['ID'] = amazon['ID'].astype('int64')
amazon = amazon[amazon['ID'].isin(df['ID'])]
amazon.groupby('ID').size().reset_index(name='Total')['Total'].describe()

count    569.000000
mean      20.936731
std        7.361840
min        2.000000
25%       16.000000
50%       20.000000
75%       25.000000
max       50.000000
Name: Total, dtype: float64

In [27]:
data_test.groupby('ID').size().reset_index(name='Total')['Total'].describe()

count    569.000000
mean       9.826011
std        3.015154
min        1.000000
25%        8.000000
50%       10.000000
75%       12.000000
max       16.000000
Name: Total, dtype: float64

In [25]:
qtn_class['Total'].describe()

count    381.000000
mean      14.674541
std       35.394604
min        1.000000
25%        1.000000
50%        3.000000
75%       11.000000
max      406.000000
Name: Total, dtype: float64

### Quantidade de classes

In [10]:
qtn = 50

In [11]:
qtn_class.tail(qtn)

                     Class  Total
106                Exposed     31
343                    Top     31
216                 Muscle     31
214                  Mouth     31
99           Electric blue     32
378                Wrinkle     32
111                Eyewear     32
292                    Sky     34
115                    Fan     35
15         Audio equipment     36
110                Eyelash     36
151                   Hair     38
157                   Head     38
152              Hairstyle     39
109                Eyebrow     40
175                    Jaw     40
259  Public address system     40
103          Entertainment     42
114            Facial hair     42
138                    Fun     43
81                   Crowd     48
65                Clothing     50
165                  Human     51
321                T-shirt     54
69                  Collar     54
67                    Coat     55
143                Glasses     56
113      Facial expression     58
32                  Blazer     58
377                  World     64
95             Dress shirt     64
256                Product     70
34                 Blurred     70
316                   Suit     71
230                   Nose     72
27                   Beard     74
154                  Happy     91
302           Spokesperson     99
294                 Sleeve    100
203             Microphone    114
104                  Event    119
337                    Tie    126
57                    Chin    127
295                  Smile    132
156                    Hat    133
130                   Font    172
133               Forehead    173
142                Gesture    212
180                    Joy    242
242                 Person    406

## Novo dataframe com classes em dummy e ID

In [12]:
new_data = new_data[np.append(qtn_class['Class'].tail(qtn).values, 'ID')]
new_data

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person,ID
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,7114971700365692165
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7115033431473474822
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,7115050482179050758
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7115120078982630661
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,7115161088219565317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7160017587160485125
565,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7160037888611126534
566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,7160041692911930630
567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,7160077729751207174
568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7160091637970963718

## Verificando quantas classes ficam por post

In [13]:
def verify(data: pd.DataFrame, lista):
  if len(lista) == 1:
    return data.loc[data[lista[0]] == 0]
  return verify(data.loc[data[lista[0]] == 0], lista[1: ])

In [14]:
print(f'Todos os valores que não possuem nenhuma frequência das {qtn} classes mais frequentes')
verify(new_data, qtn_class.tail(qtn)["Class"].values)[np.append('ID', qtn_class['Class'].tail(qtn).values, )]

Todos os valores que não possuem nenhuma frequência das 50 classes mais frequentes

,ID,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,...,Event,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person
73,7121357518953090310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93,7122918545314417925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
232,7135609362550148357,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260,7137338570527755525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
379,7146249449340226821,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
482,7155282520869735686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Fazendo merge dos dados com base no ID

In [15]:
data_final = new_data.merge(df, on='ID', how='outer')

## Filtrando colunas para os dados

In [16]:
columns =  np.append(qtn_class['Class'].tail(qtn).values, [
  'ID',
  'Perfil',
  #'DataColeta',
  #'DataPost',
  'DiaDaSemana',
  #'Plays',                 Colunas que podem causar vazamento das informações
  #'Comentarios',
  #'Compart.',
  #'Texto',               Decidir o que fazer com essa coluna 
  #'LinkFoto',
  #'LinkVideo',             Links não são pertinentes
  #'LinkPost',
  'Duracao',
  #'Duração Classificada',
  #'Retórica Aristotélica',
  #'Dispositivo Retórico',
  #'Tipo de conteúdo',      Classificações manual
  #'Abordagem',
  #'Tonalidade',
  #'Main character',
  'Texto / Hashtag',
  'Curtidas',
])

## Salvando resultado final

In [17]:
data_final = data_final[columns]
data_final.columns

Index(['Exposed', 'Top', 'Muscle', 'Mouth', 'Electric blue', 'Wrinkle',
       'Eyewear', 'Sky', 'Fan', 'Audio equipment', 'Eyelash', 'Hair', 'Head',
       'Hairstyle', 'Eyebrow', 'Jaw', 'Public address system', 'Entertainment',
       'Facial hair', 'Fun', 'Crowd', 'Clothing', 'Human', 'T-shirt', 'Collar',
       'Coat', 'Glasses', 'Facial expression', 'Blazer', 'World',
       'Dress shirt', 'Product', 'Blurred', 'Suit', 'Nose', 'Beard', 'Happy',
       'Spokesperson', 'Sleeve', 'Microphone', 'Event', 'Tie', 'Chin', 'Smile',
       'Hat', 'Font', 'Forehead', 'Gesture', 'Joy', 'Person', 'ID', 'Perfil',
       'DiaDaSemana', 'Duracao', 'Texto / Hashtag', 'Curtidas'],
      dtype='object')

In [18]:
data_final['Duracao'] = pd.to_numeric(data_final['Duracao'], errors='coerce', downcast='signed')
data_final = pd.get_dummies(data_final, columns=['DiaDaSemana', 'Perfil'], prefix='', prefix_sep='', dtype='int',)
data_final.drop('lulaoficial', axis=1, inplace=True)
data_final.rename({'bolsonaromessiasjair': 'Perfil'}, axis=1, inplace=True)

## OBS na coluna perfil os valores repesentam
- 1 == bolsonaromessiasjair
- 0 == lulaoficial

In [19]:
data_final = pd.get_dummies(data_final, columns=['Texto / Hashtag'], prefix='', prefix_sep='', dtype='int')
aux = data_final['Texto + Hashtag'].apply(lambda x: 1 if x==1 else 0).astype('int32')
aux = pd.DataFrame({"Texto":aux.values, "Hashtag":aux.values})
data_final['Texto'] = aux['Texto'] + data_final['Texto']
data_final['Hashtag'] = aux['Texto'] + data_final['Hashtag']
data_final.drop(['Texto + Hashtag', 'Nenhum'], inplace=True, axis=1)

In [20]:
data_final.sort_values('ID', inplace=True)
data_final.set_index('ID', inplace=True)

In [21]:
data_final

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,domingo,quarta-feira,quinta-feira,segunda-feira,sexta-feira,sábado,terça-feira,Perfil,Hashtag,Texto
ID,,,,,,,,,,,,,,,,,,,,,
7114971700365692165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,1,0,0,0,0,1,1,0
7115033431473474822,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,1,1
7115050482179050758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,1,0
7115120078982630661,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,1,0
7115161088219565317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7160017587160485125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,1,0,1,1,1
7160037888611126534,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1
7160041692911930630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1
7160077729751207174,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1
7160091637970963718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1

In [22]:
data_final.columns

Index(['Exposed', 'Top', 'Muscle', 'Mouth', 'Electric blue', 'Wrinkle',
       'Eyewear', 'Sky', 'Fan', 'Audio equipment', 'Eyelash', 'Hair', 'Head',
       'Hairstyle', 'Eyebrow', 'Jaw', 'Public address system', 'Entertainment',
       'Facial hair', 'Fun', 'Crowd', 'Clothing', 'Human', 'T-shirt', 'Collar',
       'Coat', 'Glasses', 'Facial expression', 'Blazer', 'World',
       'Dress shirt', 'Product', 'Blurred', 'Suit', 'Nose', 'Beard', 'Happy',
       'Spokesperson', 'Sleeve', 'Microphone', 'Event', 'Tie', 'Chin', 'Smile',
       'Hat', 'Font', 'Forehead', 'Gesture', 'Joy', 'Person', 'Duracao',
       'Curtidas', 'domingo', 'quarta-feira', 'quinta-feira', 'segunda-feira',
       'sexta-feira', 'sábado', 'terça-feira', 'Perfil', 'Hashtag', 'Texto'],
      dtype='object')

In [36]:
data_final.corr()

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,domingo,quarta-feira,quinta-feira,segunda-feira,sexta-feira,sábado,terça-feira,Perfil,Hashtag,Texto
Exposed,1.000000,0.010613,-0.057621,-0.057621,-0.024987,-0.058597,-0.024987,0.102827,0.164143,-0.030577,...,-0.014407,-0.001971,-0.040389,-0.007987,0.058842,0.008941,-0.003200,0.089825,-0.000855,-0.041631
Top,0.010613,1.000000,0.112963,0.010613,0.008624,-0.058597,0.075846,-0.060514,-0.061454,-0.062385,...,-0.038589,0.020919,0.086932,-0.007987,-0.074815,0.029128,-0.025962,0.012126,-0.000855,-0.010005
Muscle,-0.057621,0.112963,1.000000,0.010613,-0.058597,-0.058597,0.075846,-0.060514,0.003002,0.001230,...,-0.062770,0.020919,0.002051,-0.007987,0.014290,0.008941,0.019562,-0.050033,0.043386,0.037434
Mouth,-0.057621,0.010613,0.010613,1.000000,-0.058597,0.042235,-0.058597,-0.060514,-0.061454,-0.030577,...,0.009775,0.089589,0.065712,-0.030263,-0.052539,-0.071809,-0.003200,0.027666,-0.000855,-0.025818
Electric blue,-0.024987,0.008624,-0.058597,-0.058597,1.000000,-0.026478,-0.026478,-0.029355,-0.062496,-0.063442,...,-0.040779,-0.004914,0.040525,0.010992,0.010992,-0.054421,0.038701,-0.117550,0.000536,0.120986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sábado,0.008941,0.029128,0.008941,-0.071809,-0.054421,-0.114085,-0.034533,0.114147,0.090121,-0.046176,...,-0.169289,-0.182100,-0.202579,-0.189031,-0.189031,1.000000,-0.183495,0.029541,-0.046422,0.006479
terça-feira,-0.003200,-0.025962,0.019562,-0.003200,0.038701,-0.006148,-0.006148,-0.055389,0.006991,-0.017156,...,-0.142223,-0.152986,-0.170191,-0.158809,-0.158809,-0.183495,1.000000,-0.050400,-0.017586,0.066675
Perfil,0.089825,0.012126,-0.050033,0.027666,-0.117550,-0.148169,-0.010386,0.095294,0.072598,0.050516,...,0.019009,0.006230,0.026262,-0.057794,0.023378,0.029541,-0.050400,1.000000,-0.156040,-0.841808
Hashtag,-0.000855,-0.000855,0.043386,-0.000855,0.000536,0.044121,0.044121,0.045564,0.046273,0.046973,...,-0.028602,0.011059,0.023310,0.073106,-0.013555,-0.046422,-0.017586,-0.156040,1.000000,0.057805
Texto,-0.041631,-0.010005,0.037434,-0.025818,0.120986,0.136565,-0.003641,-0.097449,-0.015489,-0.053633,...,-0.018713,-0.022058,-0.059947,0.061079,-0.031846,0.006479,0.066675,-0.841808,0.057805,1.000000

In [23]:
data_final.to_csv('data/dfGoogle.csv')
data_final.to_excel('data/dfGoogle.xlsx')