In [32]:
import pandas as pd
import numpy as np
import datetime

In [33]:
df = pd.read_excel('data/Bolsonaro + Lula - Validado.xlsx')
df

,Unnamed: 0,DataColeta,Perfil,DataPost,DiaDaSemana,Plays,Curtidas,Comentarios,Compart.,Texto,...,ID,Duracao,Duração Classificada,Retórica Aristotélica,Dispositivo Retórico,Tipo de conteúdo,Abordagem,Tonalidade,Main character,Texto / Hashtag
0,1,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,248400,24400,1083,1566,#jairbolsonaro #bolsonaro #palavras #president...,...,7114971700365692165,57.93,Curto,Pathos,Political Statement,Campaign Act,Acclamation,Neutral,Self alone,Hashtag
1,2,2022-10-02,lulaoficial,2022-06-30 00:00:00,quinta-feira,196800,11700,809,589,Alô alô geração tiktoker! Imagina só um #gover...,...,7115033431473474822,2023-03-17 00:00:00,Muito curto,Pathos,Political Statement,Political-Purposeful,Acclamation,Neutral,Self alone,Texto + Hashtag
2,3,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,82000,9163,480,1140,#emprego #jair #bolsonaro #jairbolsonaro #pres...,...,7115050482179050758,17.13,Muito curto,Logos,Fact/Statistic,Political-Purposeful,Acclamation,Positive,Self alone,Hashtag
3,4,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,42300,3485,198,355,#jairbolsonaro #bolsonaro #jair #presidente #m...,...,7115120078982630661,52.54,Curto,Ethos,Commitment,Political-Purposeful,Acclamation,Positive,Self + voters,Hashtag
4,5,2022-10-02,bolsonaromessiasjair,2022-06-30 00:00:00,quinta-feira,168500,22100,666,967,#jairbolsonaro #bolsonaro #brasil #descontraca...,...,7115161088219565317,34.48,Curto,Nenhum,Humor,Personal,Acclamation,Positive,Self alone,Hashtag
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,565,2022-10-30,bolsonaromessiasjair,2022-10-29 17:13:46,sábado,191600,23500,1611,1499,- Belo Horizonte/MG. - Presidente Jair Bolsona...,...,7160017587160485125,51.34,Curto,Ethos,Commitment,Campaign Act,Acclamation,Positive,Self + voters,Texto + Hashtag
565,566,2022-10-30,lulaoficial,2022-10-29 17:52:50,sábado,322000,33900,540,1361,Todo mundo tem um vizinho que vota pela famíli...,...,7160037888611126534,2023-02-15 00:00:00,Muito curto,Ethos,Advertisement,Campaign Act,Acclamation,Positive,Nenhum,Texto + Hashtag
566,567,2022-10-30,lulaoficial,2022-10-29 18:52:45,sábado,317800,25000,1166,2525,Lula criou o mei e vai fazer ainda mais pelo p...,...,7160041692911930630,85.1,Normal,Ethos,Political Statement,Political-Purposeful,Attack,Negative,Self alone,Texto + Hashtag
567,568,2022-10-30,lulaoficial,2022-10-29 20:52:41,sábado,60700,4807,374,826,Ta chegando a hora de votar #lulapresidente #lula,...,7160077729751207174,12.93,Muito curto,Ethos,Advertisement,Campaign Act,Acclamation,Positive,Self alone,Texto + Hashtag
568,569,2022-10-30,lulaoficial,2022-10-29 21:52:34,sábado,107800,17100,965,2338,Obrigado São Paulo ❤️🇧🇷🇧🇷1️⃣3️⃣⭐️ #lulapreside...,...,7160091637970963718,49.19,Curto,Ethos,Thanks,Campaign Act,Acclamation,Positive,Self alone,Texto + Hashtag

## Tratando coluna de duração

In [34]:
def day_for_flaot(x):
  if(isinstance(x, datetime.datetime)):
    x = float(f"{x.day}.{x.month}")
  return x

In [35]:
df['Duracao'] = df['Duracao'].apply(day_for_flaot)

## Observando primeiro quartil antes e depois do filtro de porcentagem

In [36]:
data = pd.read_csv('data/GoogleVision.csv')
data = data.loc[data['ID'].isin(df['ID'])] # Filtrando post que estão no dataset do tiktok
data = data.loc[data['Subclass'] != 'text']
data_test = data.loc[data['Percent'] >= 0.74]

In [37]:
print('Dados anteriores')
print('Quantidade de IDs:', len(data['ID'].unique()))
print('Quantidade de de classes:', data['ID'].count())
print('Mediana:', data['Percent'].median())
print('Média:', data['Percent'].mean())
print('1º Quartil:', data['Percent'].quantile(.25))
print('-----------------------------')
print('Dados posteriores')
print('Quantidade de IDs:', len(data_test['ID'].unique()))
print('Quantidade de de classes:', data_test['ID'].count())
print('Mediana:', data_test['Percent'].median())
print('Média:', data_test['Percent'].mean())
print('1º Quartil:', data_test['Percent'].quantile(.25))

Dados anteriores
Quantidade de IDs: 569
Quantidade de de classes: 7221
Mediana: 0.83
Média: 0.8233970364215483
1º Quartil: 0.74
-----------------------------
Dados posteriores
Quantidade de IDs: 569
Quantidade de de classes: 5591
Mediana: 0.87
Média: 0.8719477732069396
1º Quartil: 0.8

## Montando dataset com colunas em dummy

In [38]:
new_data = []
for id in data_test['ID'].unique():
  row = {'ID': id}
  for classe in data_test.loc[data_test['ID'] == id]['Class'].values:
    row[classe] = 1
  new_data.append(row)

new_data = pd.DataFrame(new_data)
new_data.fillna(0, inplace=True)
print(new_data)

                      ID  Public address system  Face  Spokesperson  \
0    7114971700365692165                    1.0   1.0           1.0
1    7115033431473474822                    0.0   0.0           0.0
2    7115050482179050758                    0.0   0.0           0.0
3    7115120078982630661                    0.0   0.0           0.0
4    7115161088219565317                    0.0   0.0           1.0
..                   ...                    ...   ...           ...
564  7160017587160485125                    0.0   0.0           0.0
565  7160037888611126534                    0.0   0.0           0.0
566  7160041692911930630                    0.0   0.0           1.0
567  7160077729751207174                    0.0   0.0           0.0
568  7160091637970963718                    0.0   0.0           0.0

     Audio equipment  Forehead  Gesture  Head  Person  Microphone  ...  Fluid  \
0                1.0       1.0      1.0   1.0     1.0         1.0  ...    0.0
1                0.0       1.0      1.0   0.0     0.0         0.0  ...    0.0
2                0.0       1.0      0.0   0.0     0.0         0.0  ...    0.0
3                0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
4                0.0       0.0      1.0   0.0     1.0         1.0  ...    0.0
..               ...       ...      ...   ...     ...         ...  ...    ...
564              0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
565              0.0       0.0      0.0   0.0     1.0         0.0  ...    0.0
566              0.0       0.0      1.0   0.0     1.0         1.0  ...    0.0
567              0.0       1.0      0.0   0.0     1.0         0.0  ...    0.0
568              0.0       0.0      0.0   0.0     0.0         0.0  ...    0.0

     Guitar  Guitar accessory  String instrument accessory  Speaker  \
0       0.0               0.0                          0.0      0.0
1       0.0               0.0                          0.0      0.0
2       0.0               0.0                          0.0      0.0
3       0.0               0.0                          0.0      0.0
4       0.0               0.0                          0.0      0.0
..      ...               ...                          ...      ...
564     0.0               0.0                          0.0      0.0
565     0.0               0.0                          0.0      0.0
566     0.0               0.0                          0.0      0.0
567     0.0               0.0                          0.0      0.0
568     0.0               0.0                          0.0      0.0

     Serveware  Drinkware  Coffee cup  Cup  Vegetation
0          0.0        0.0         0.0  0.0         0.0
1          0.0        0.0         0.0  0.0         0.0
2          0.0        0.0         0.0  0.0         0.0
3          0.0        0.0         0.0  0.0         0.0
4          0.0        0.0         0.0  0.0         0.0
..         ...        ...         ...  ...         ...
564        0.0        0.0         0.0  0.0         0.0
565        0.0        0.0         0.0  0.0         0.0
566        0.0        0.0         0.0  0.0         0.0
567        0.0        0.0         0.0  0.0         0.0
568        0.0        0.0         0.0  0.0         1.0

[569 rows x 382 columns]

## Pegando quantidade de classes mais presentes nos dados

In [39]:
qtn_class = data_test.groupby('Class').size().reset_index(name='Total').sort_values('Total')
qtn_class

              Class  Total
0           Abdomen      1
304          Sports      1
303     Sport venue      1
117  Fashion design      1
119           Fence      1
..              ...    ...
130            Font    172
133        Forehead    173
142         Gesture    212
180             Joy    242
242          Person    406

[381 rows x 2 columns]

### Quantidade de classes

In [40]:
qtn = 10

In [41]:
qtn_class.tail(qtn)

        Class  Total
104     Event    119
337       Tie    126
57       Chin    127
295     Smile    132
156       Hat    133
130      Font    172
133  Forehead    173
142   Gesture    212
180       Joy    242
242    Person    406

## Novo dataframe com classes em dummy e ID

In [42]:
new_data = new_data[np.append(qtn_class['Class'].tail(qtn).values, 'ID')]
new_data

,Event,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person,ID
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,7114971700365692165
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7115033431473474822
2,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,7115050482179050758
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7115120078982630661
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,7115161088219565317
...,...,...,...,...,...,...,...,...,...,...,...
564,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7160017587160485125
565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7160037888611126534
566,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,7160041692911930630
567,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,7160077729751207174
568,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7160091637970963718

## Verificando quantas classes ficam por post

In [43]:
def verify(data: pd.DataFrame, lista):
  if len(lista) == 1:
    return data.loc[data[lista[0]] == 0]
  return verify(data.loc[data[lista[0]] == 0], lista[1: ])

In [44]:
print(f'Todos os valores que não possuem nenhuma frequência das {qtn} classes mais frequentes')
verify(new_data, qtn_class.tail(qtn)["Class"].values)[np.append('ID', qtn_class['Class'].tail(qtn).values, )]

Todos os valores que não possuem nenhuma frequência das 10 classes mais frequentes

,ID,Event,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person
73,7121357518953090310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93,7122918545314417925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,7123910264365387013,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,7124436611969862918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,7126288473073487110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,7128066426392284421,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
232,7135609362550148357,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260,7137338570527755525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
320,7141387420041301254,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
374,7145806251039984901,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
379,7146249449340226821,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
441,7151733451157261573,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
482,7155282520869735686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
507,7157004669003386118,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
513,7157335164136230149,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
552,7159624979728878854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Fazendo merge dos dados com base no ID

In [45]:
data_final = new_data.merge(df, on='ID', how='outer')

## Filtrando colunas para os dados

In [46]:
columns =  np.append(qtn_class['Class'].tail(qtn).values, [
  'ID', 
  #'DataColeta', 
  'Perfil', 
  #'DataPost', 
  'DiaDaSemana',
  #'Plays',                 Colunas que podem causar vazamento das informações
  #'Comentarios', 
  #'Compart.', 
  #'Texto',               Decidir o que fazer com essa coluna 
  #'LinkFoto',
  #'LinkVideo',             Links não são pertinentes
  #'LinkPost', 
  'Duracao', 
  #'Duração Classificada',
  #'Retórica Aristotélica', 
  #'Dispositivo Retórico', 
  #'Tipo de conteúdo',      Classificações manual
  #'Abordagem', 
  #'Tonalidade', 
  #'Main character', 
  'Texto / Hashtag',
  'Curtidas', 
])

## Salvando resultado final

In [47]:
data_final = data_final[columns]
data_final.columns

Index(['Event', 'Tie', 'Chin', 'Smile', 'Hat', 'Font', 'Forehead', 'Gesture',
       'Joy', 'Person', 'ID', 'Perfil', 'DiaDaSemana', 'Duracao',
       'Texto / Hashtag', 'Curtidas'],
      dtype='object')

In [48]:
data_final['Duracao'] = pd.to_numeric(data_final['Duracao'], errors='coerce', downcast='signed')
data_final = pd.get_dummies(data_final, columns=['DiaDaSemana', 'Perfil'], prefix='', prefix_sep='', dtype='int',)
data_final.drop('lulaoficial', axis=1, inplace=True)
data_final.rename({'bolsonaromessiasjair': 'Perfil'}, axis=1, inplace=True)

## OBS na coluna perfil os valores repesentam
- 1 == bolsonaromessiasjair
- 0 == lulaoficial

In [49]:
data_final = pd.get_dummies(data_final, columns=['Texto / Hashtag'], prefix='', prefix_sep='', dtype='int')
aux = data_final['Texto + Hashtag'].apply(lambda x: 1 if x==1 else 0).astype('int32')
aux = pd.DataFrame({"Texto":aux.values, "Hashtag":aux.values})
data_final['Texto'] = aux['Texto'] + data_final['Texto']
data_final['Hashtag'] = aux['Texto'] + data_final['Hashtag']
data_final.drop(['Texto + Hashtag', 'Nenhum'], inplace=True, axis=1)

In [50]:
data_final.sort_values('ID', inplace=True)
data_final.set_index('ID', inplace=True)

In [52]:
data_final

,Event,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person,...,domingo,quarta-feira,quinta-feira,segunda-feira,sexta-feira,sábado,terça-feira,Perfil,Hashtag,Texto
ID,,,,,,,,,,,,,,,,,,,,,
7114971700365692165,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,0,0,1,0,0,0,0,1,1,0
7115033431473474822,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0,0,1,0,0,0,0,0,1,1
7115050482179050758,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0,0,1,0,0,0,0,1,1,0
7115120078982630661,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,1,0,0,0,0,1,1,0
7115161088219565317,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7160017587160485125,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,1,1,1
7160037888611126534,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,1,1
7160041692911930630,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0,0,0,0,0,1,0,0,1,1
7160077729751207174,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0,0,0,0,0,1,0,0,1,1
7160091637970963718,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1

In [53]:
data_final.columns

Index(['Event', 'Tie', 'Chin', 'Smile', 'Hat', 'Font', 'Forehead', 'Gesture',
       'Joy', 'Person', 'Duracao', 'Curtidas', 'domingo', 'quarta-feira',
       'quinta-feira', 'segunda-feira', 'sexta-feira', 'sábado', 'terça-feira',
       'Perfil', 'Hashtag', 'Texto'],
      dtype='object')

In [51]:
#data_final.to_csv('data/dfGoogle.csv')
#data_final.to_excel('data/dfGoogle.xlsx')