In [210]:
import pandas as pd
import numpy as np
import datetime

In [211]:
df = pd.read_excel('data/Bolsonaro + Lula - Validado.xlsx')

## Tratando coluna de duração

In [212]:
def day_for_flaot(x):
  if(isinstance(x, datetime.datetime)):
    x = float(f"{x.day}.{x.month}")
  print(x)
  return x

In [213]:
df['Duracao'] = df['Duracao'].apply(day_for_flaot)

57.93
17.3
17.13
52.54
34.48
60.16
66.66
14.88
48.71
74.07
15.39
51.48
60.93
21.57
12.75
35.22
16.18
45.04
60.18
38.68
60.11
58.19
42.07
23.99
49.5
73
60.3
127.96
54.33
49.02
9.26
60.11
53.85
47.02
52.06
15.11
65.9
24.98
21.43
57.72
30.95
43.81
25.73
9.94
60.23
12.65
5.11
60
26.47
29.19
29.16
59.6
35.71
19.62
22.15
46.55
37.45
23.82
51.36
56.79
56.63
44.51
31.16
59.95
25.24
39.08
25.7
52.45
60.21
95.64
14.58
35.25
11.65
15.23
39.54
88.23
32
45.21
52.99
60.28
49.74
43.07
20.1
26.24
21.89
33.83
60.02
8.57
16.97
26.45
96.41
55.28
26.98
27.63
41.54
25.87
50.06
58.74
57.75
59.79
39.29
33.78
7.54
18.27
28.7
43.19
60.67
31.83
50.34
18.18
46.23
71.03
32.32
17.88
23.38
43.33
38.15
42.19
36.69
76.09
12.3
37.82
11.77
58.95
62.55
24.87
54.19
59.93
49.6
41
17.2
61.88
57.89
61.46
60.23
64.25
84.5
93.3
14.32
21.22
43.21
58.16
77.32
42.58
55.56
68.78
34.13
46.32
50.66
35.62
59.79
90.3
54.8
8.87
27.7
59.3
21.29
39.89
20.92
90.14
34.69
59.16
94.13
32.62
49.36
34.83
57.14
38.54
44.21
19.85
50.15
57.79
49.41
37.5
24.59
60.16
37.27
26.56
29.39
47.23
33.18
7.92
45.72
41.89
64.06
76.3
18.62
11.33
58.54
58.72
15.23
7.86
20.59
29.23
64.9
55.35
72.12
11.47
41
65.2
56.63
43.3
57.82
42.84
6.62
17.65
21.15
11.89
52.5
8.66
22.2
58.16
9.75
36.66
90.18
27.82
15.28
81.08
7.41
20.27
59.09
61.53
31.28
59.12
98.08
54.84
17.11
47.14
41.05
60.21
22.71
60.81
60.33
10.21
38.91
30.32
40.26
67.27
77.65
62.02
15.21
27.49
60.35
46.02
81.01
6.1
52.43
56.03
90.53
90.21
219.4
14.14
64.85
24.8
37.8
5.94
33.42
77.51
57.54
88.44
14.49
73.81
85.54
13.91
38.8
84.63
6.29
35.43
31.53
48.64
28.4
40.7
72.51
42.98
15.63
55.56
42.98
22.8
28.44
26.7
30.88
12.35
49.85
6.96
25.56
16.31
54.87
41.26
30.23
51.62
29.88
21.99
20.15
28.67
55.49
25.1
75.18
77.99
29.46
139.83
18.43
28.98
8.47
28.16
11.42
39.98
13.12
16.97
26.82
128.96
14.7
18.71
8.61
79.97
11.17
86.63
36.36
17.2
45.56
57.96
30.11
11.91
33.3
70.33
15.18
66.48
18.71
30.3
62.97
51.45
10.8
26.19
89.91
17.74
19.2
90.16
45.37
8.54
41.98
42.47
79.27
42.79
7.89
46.39
44.14
15.42
29.7
23.68
56.31
52.52
43.61
73.28
14.5
82.48
32.37
14.95
56.49
14.42
29.74
64.25
33.41
16.65
60.28
53.59
38.31
54.73
8.3
63.86
59.6
41.8
21.5
59.05
65.46
51.66
25.1
8.19
174.05
45.46
15
30.32
9.68
55.59
61.93
43.02
72.31
9.8
56.42
84.03
70.03
49.13
73.26
20.94
54.59
27.65
31.28
34.11
17.39
48.5
63.56
31.69
112.13
23.61
35.48
44.37
78.85
15.28
27.37
13.77
13.4
62.65
28
59
15.86
24.12
22.71
34.53
14.6
45.15
46.53
9.54
89.39
14.77
15.65
18.11
12.77
51.55
49.38
76.64
94.76
56.03
13.91
4.8
25.1
13.28
22.38
26.52
15.79
28.81
93.67
7.66
42.17
14.9
130.61
30.28
41.28
15.23
63.92
20.1
46.23
36.8
88.03
36.99
12.7
15.53
34.2
9.43
61.47
33.55
43.09
45.32
67.78
37.97
53.85
33.67
41.28
10.35
28.26
13.77
40.84
56.4
61.79
12.56
19.6
34.48
18.69
64.2
30.3
72.98
28.88
76.35
65.8
18.67
21.97
93.57
15.4
57.3
25.3
36.71
30.14
67.24
80.92
36.52
68.9
52.9
23.18
54.3
117.03
42.81
54.82
26.14
28.16
24.46
13.68
71.59
13.96
60.04
38.03
38.92
60.88
79.02
50.43
41.1
44.6
82.1
72.74
9.99
55.54
45.76
21.41
17
97.85
19.62
40.52
89.21
78.2
52.81
12.51
31.95
45.3
116.03
9.24
34.67
55.66
6.66
84.98
13.72
73.58
185.31
45.6
67.81
66.71
67.22
188.29
14.98
32.83
45.42
68.81
24.54
15.31
63.41
25.45
47.62
32.81
17.48
8.8
17.48
126.94
43.19
74.16
5.32
7.73
8.38
42.1
86.36
51.34
15.2
85.1
12.93
49.19

## Observando primeiro quartil antes e depois do filtro de porcentagem

In [214]:
data = pd.read_csv('data/GoogleVision.csv')
data = data.loc[data['ID'].isin(df['ID'])] # Filtrando post que estão no dataset do tiktok
data = data.loc[data['Subclass'] != 'text']
data_test = data.loc[data['Percent'] >= 0.74]

In [215]:
print('Dados anteriores')
print('Quantidade de IDs:', len(data['ID'].unique()))
print('Quantidade de de classes:', data['ID'].count())
print('Mediana:', data['Percent'].median())
print('Média:', data['Percent'].mean())
print('1º Quartil:', data['Percent'].quantile(.25))
print('-----------------------------')
print('Dados posteriores')
print('Quantidade de IDs:', len(data_test['ID'].unique()))
print('Quantidade de de classes:', data_test['ID'].count())
print('Mediana:', data_test['Percent'].median())
print('Média:', data_test['Percent'].mean())
print('1º Quartil:', data_test['Percent'].quantile(.25))

Dados anteriores
Quantidade de IDs: 569
Quantidade de de classes: 7221
Mediana: 0.83
Média: 0.8233970364215483
1º Quartil: 0.74
-----------------------------
Dados posteriores
Quantidade de IDs: 569
Quantidade de de classes: 5591
Mediana: 0.87
Média: 0.8719477732069396
1º Quartil: 0.8

## Montando dataset com colunas em dummy

In [216]:
new_data = []
for id in data_test['ID'].unique():
  row = {'ID': id}
  for classe in data_test.loc[data_test['ID'] == id]['Class'].values:
    row[classe] = 1
  new_data.append(row)

In [217]:
new_data = pd.DataFrame(new_data)
new_data.fillna(0, inplace=True)
new_data

,ID,Public address system,Face,Spokesperson,Audio equipment,Forehead,Gesture,Head,Person,Microphone,...,Fluid,Guitar,Guitar accessory,String instrument accessory,Speaker,Serveware,Drinkware,Coffee cup,Cup,Vegetation
0,7114971700365692165,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7115033431473474822,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7115050482179050758,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7115120078982630661,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7115161088219565317,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,7160017587160485125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
565,7160037888611126534,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
566,7160041692911930630,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
567,7160077729751207174,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
568,7160091637970963718,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## Pegando quantidade de classes mais presentes nos dados

In [218]:
qtn_class = data_test.groupby('Class').size().reset_index(name='Total').sort_values('Total')
qtn_class

              Class  Total
0           Abdomen      1
304          Sports      1
303     Sport venue      1
117  Fashion design      1
119           Fence      1
..              ...    ...
130            Font    172
133        Forehead    173
142         Gesture    212
180             Joy    242
242          Person    406

[381 rows x 2 columns]

In [219]:
qtn = 50

In [220]:
qtn_class.tail(qtn)

                     Class  Total
106                Exposed     31
343                    Top     31
216                 Muscle     31
214                  Mouth     31
99           Electric blue     32
378                Wrinkle     32
111                Eyewear     32
292                    Sky     34
115                    Fan     35
15         Audio equipment     36
110                Eyelash     36
151                   Hair     38
157                   Head     38
152              Hairstyle     39
109                Eyebrow     40
175                    Jaw     40
259  Public address system     40
103          Entertainment     42
114            Facial hair     42
138                    Fun     43
81                   Crowd     48
65                Clothing     50
165                  Human     51
321                T-shirt     54
69                  Collar     54
67                    Coat     55
143                Glasses     56
113      Facial expression     58
32                  Blazer     58
377                  World     64
95             Dress shirt     64
256                Product     70
34                 Blurred     70
316                   Suit     71
230                   Nose     72
27                   Beard     74
154                  Happy     91
302           Spokesperson     99
294                 Sleeve    100
203             Microphone    114
104                  Event    119
337                    Tie    126
57                    Chin    127
295                  Smile    132
156                    Hat    133
130                   Font    172
133               Forehead    173
142                Gesture    212
180                    Joy    242
242                 Person    406

In [221]:
new_data = new_data[np.append(qtn_class['Class'].tail(qtn).values, 'ID')]
new_data

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person,ID
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,7114971700365692165
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,7115033431473474822
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,7115050482179050758
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7115120078982630661
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,7115161088219565317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7160017587160485125
565,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7160037888611126534
566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,7160041692911930630
567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,7160077729751207174
568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,7160091637970963718

## Verificando quantas classes ficam por post

In [222]:
def verify(data: pd.DataFrame, lista):
  if len(lista) == 1:
    return data.loc[data[lista[0]] == 0]
  return verify(data.loc[data[lista[0]] == 0], lista[1: ])

In [223]:
verify(new_data, qtn_class.tail(qtn)["Class"].values)

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,Tie,Chin,Smile,Hat,Font,Forehead,Gesture,Joy,Person,ID
73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7121357518953090310
93,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7122918545314417925
232,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7135609362550148357
260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7137338570527755525
379,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7146249449340226821
482,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7155282520869735686

# Fazendo merge dos dados com base no ID

In [224]:
data_final = new_data.merge(df, on='ID', how='outer')
data_final.columns

Index(['Exposed', 'Top', 'Muscle', 'Mouth', 'Electric blue', 'Wrinkle',
       'Eyewear', 'Sky', 'Fan', 'Audio equipment', 'Eyelash', 'Hair', 'Head',
       'Hairstyle', 'Eyebrow', 'Jaw', 'Public address system', 'Entertainment',
       'Facial hair', 'Fun', 'Crowd', 'Clothing', 'Human', 'T-shirt', 'Collar',
       'Coat', 'Glasses', 'Facial expression', 'Blazer', 'World',
       'Dress shirt', 'Product', 'Blurred', 'Suit', 'Nose', 'Beard', 'Happy',
       'Spokesperson', 'Sleeve', 'Microphone', 'Event', 'Tie', 'Chin', 'Smile',
       'Hat', 'Font', 'Forehead', 'Gesture', 'Joy', 'Person', 'ID',
       'Unnamed: 0', 'DataColeta', 'Perfil', 'DataPost', 'DiaDaSemana',
       'Plays', 'Curtidas', 'Comentarios', 'Compart.', 'Texto', 'LinkFoto',
       'LinkVideo', 'LinkPost', 'Duracao', 'Duração Classificada',
       'Retórica Aristotélica', 'Dispositivo Retórico', 'Tipo de conteúdo',
       'Abordagem', 'Tonalidade', 'Main character', 'Texto / Hashtag'],
      dtype='object')

# Filtrando colunas para os dados

In [225]:
df.columns

Index(['Unnamed: 0', 'DataColeta', 'Perfil', 'DataPost', 'DiaDaSemana',
       'Plays', 'Curtidas', 'Comentarios', 'Compart.', 'Texto', 'LinkFoto',
       'LinkVideo', 'LinkPost', 'ID', 'Duracao', 'Duração Classificada',
       'Retórica Aristotélica', 'Dispositivo Retórico', 'Tipo de conteúdo',
       'Abordagem', 'Tonalidade', 'Main character', 'Texto / Hashtag'],
      dtype='object')

In [228]:
columns =  np.append(qtn_class['Class'].tail(qtn).values, [
  'ID', 
  #'DataColeta', 
  'Perfil', 
  #'DataPost', 
  'DiaDaSemana',
  #'Plays',                 Colunas que podem causar vazamento das informações
  #'Comentarios', 
  #'Compart.', 
  'Texto', 
  #'LinkFoto',
  #'LinkVideo',             Links não são pertinentes
  #'LinkPost', 
  'Duracao', 
  'Duração Classificada',
  #'Retórica Aristotélica', 
  #'Dispositivo Retórico', 
  #'Tipo de conteúdo',      Classificações manual
  #'Abordagem', 
  #'Tonalidade', 
  #'Main character', 
  'Texto / Hashtag',
  'Curtidas', 
  ])

## Salvando resultado final

In [229]:
data_final = data_final[columns]
data_final

,Exposed,Top,Muscle,Mouth,Electric blue,Wrinkle,Eyewear,Sky,Fan,Audio equipment,...,Joy,Person,ID,Perfil,DiaDaSemana,Texto,Duracao,Duração Classificada,Texto / Hashtag,Curtidas
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,7114971700365692165,bolsonaromessiasjair,quinta-feira,#jairbolsonaro #bolsonaro #palavras #president...,57.93,Curto,Hashtag,24400
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7115033431473474822,lulaoficial,quinta-feira,Alô alô geração tiktoker! Imagina só um #gover...,17.3,Muito curto,Texto + Hashtag,11700
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,7115050482179050758,bolsonaromessiasjair,quinta-feira,#emprego #jair #bolsonaro #jairbolsonaro #pres...,17.13,Muito curto,Hashtag,9163
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,7115120078982630661,bolsonaromessiasjair,quinta-feira,#jairbolsonaro #bolsonaro #jair #presidente #m...,52.54,Curto,Hashtag,3485
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,7115161088219565317,bolsonaromessiasjair,quinta-feira,#jairbolsonaro #bolsonaro #brasil #descontraca...,34.48,Curto,Hashtag,22100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,7160017587160485125,bolsonaromessiasjair,sábado,- Belo Horizonte/MG. - Presidente Jair Bolsona...,51.34,Curto,Texto + Hashtag,23500
565,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,7160037888611126534,lulaoficial,sábado,Todo mundo tem um vizinho que vota pela famíli...,15.2,Muito curto,Texto + Hashtag,33900
566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,7160041692911930630,lulaoficial,sábado,Lula criou o mei e vai fazer ainda mais pelo p...,85.1,Normal,Texto + Hashtag,25000
567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,7160077729751207174,lulaoficial,sábado,Ta chegando a hora de votar #lulapresidente #lula,12.93,Muito curto,Texto + Hashtag,4807
568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7160091637970963718,lulaoficial,sábado,Obrigado São Paulo ❤️🇧🇷🇧🇷1️⃣3️⃣⭐️ #lulapreside...,49.19,Curto,Texto + Hashtag,17100

In [230]:
data_final.sort_values('ID', inplace=True)
data_final.set_index('ID')
data_final['Duracao'] = pd.to_numeric(data_final['Duracao'], errors='coerce', downcast='signed')
data_final.to_excel('data/dfGoogle.xlsx')

C:\Users\José Eliodoro\AppData\Local\Temp\ipykernel_20204\3880062993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final.sort_values('ID', inplace=True)
C:\Users\José Eliodoro\AppData\Local\Temp\ipykernel_20204\3880062993.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final['Duracao'] = pd.to_numeric(data_final['Duracao'], errors='coerce', downcast='signed')

In [236]:
data_final = pd.get_dummies(data_final, columns=['DiaDaSemana'])

KeyError: "None of [Index(['DiaDaSemana'], dtype='object')] are in the [columns]"